### ISSUE TITLE
Cannot make

### ISSUE THREAD

**Issue by gadial** [niklasso/tip#1]
I followed the installation instructions in the README file, but still the make install command fails. It seems it doesn't compile some of Tip's libraries and then fails during linkage. I'm working on Kubuntu 12.10.
My output:

install -d /usr/local/include/tip
for h in tip/TipCirc.h  ; do \
          install -m 644 $h /usr/local/include/$h ; \
        done
Compiling: build/release/tip/TipCirc.o
Linking Static Library: build/release/lib/libtip.a
Compiling: build/dynamic/tip/TipCirc.o
Linking Shared Library: build/dynamic/lib/libtip.so.1.0.0
install -d /usr/local/lib
install -m 644 build/dynamic/lib/libtip.so.1.0.0 /usr/local/lib
ln -sf /usr/local/lib/libtip.so.1.0.0 /usr/local/lib/libtip.so.1
ln -sf /usr/local/lib/libtip.so.1 /usr/local/lib/libtip.so
install -m 644 build/release/lib/libtip.a /usr/local/lib
Compiling: build/release/tip/Main.o
Linking Binary: build/release/bin/tip
build/release/lib/libtip.a(TipCirc.o): In function `Tip::TipCirc::bmc(unsigned int, unsigned int, Tip::TipCirc::BmcVersion)':
/home/gadial/test/niklasso/tip/tip/TipCirc.cc:101: undefined reference to`Tip::simpBmc2(Tip::TipCirc&, unsigned int, unsigned int)'
/home/gadial/test/niklasso/tip/tip/TipCirc.cc:96: undefined reference to `Tip::basicBmc(Tip::TipCirc&, unsigned int, unsigned int, bool)'
/home/gadial/test/niklasso/tip/tip/TipCirc.cc:98: undefined reference to`Tip::simpBmc(Tip::TipCirc&, unsigned int, unsigned int)'
build/release/lib/libtip.a(TipCirc.o): In function `Tip::TipCirc::sce(bool, bool)':
/home/gadial/test/niklasso/tip/tip/TipCirc.cc:107: undefined reference to`Tip::semanticConstraintExtraction(Tip::TipCirc&, bool, bool)'
build/release/lib/libtip.a(TipCirc.o): In function `Tip::TipCirc::trip(Tip::RipBmcMode)':
/home/gadial/test/niklasso/tip/tip/TipCirc.cc:111: undefined reference to`Tip::relativeInduction(Tip::TipCirc&, Tip::RipBmcMode)'
build/release/tip/Main.o: In function `main':
/home/gadial/test/niklasso/tip/tip/Main.cc:123: undefined reference to`Tip::temporalDecompositionSmart(Tip::TipCirc&, unsigned int, unsigned int)'
/home/gadial/test/niklasso/tip/tip/Main.cc:131: undefined reference to `Tip::substituteConstraints(Tip::TipCirc&)'
/home/gadial/test/niklasso/tip/tip/Main.cc:133: undefined reference to`Tip::removeUnusedLogic(Tip::TipCirc&)'
/home/gadial/test/niklasso/tip/tip/Main.cc:138: undefined reference to `Tip::embedConstraints(Tip::TipCirc&)'
/home/gadial/test/niklasso/tip/tip/Main.cc:141: undefined reference to`Tip::embedFairness(Tip::TipCirc&)'
/home/gadial/test/niklasso/tip/tip/Main.cc:147: undefined reference to `Tip::writeLivenessBiere(Tip::TipCirc&, int, char const*)'
/home/gadial/test/niklasso/tip/tip/Main.cc:115: undefined reference to`Tip::removeUnusedLogic(Tip::TipCirc&)'
/home/gadial/test/niklasso/tip/tip/Main.cc:126: undefined reference to `Tip::fairnessConstraintExtraction(Tip::TipCirc&, int, bool)'
/home/gadial/test/niklasso/tip/tip/Main.cc:120: undefined reference to`Tip::extractSafety(Tip::TipCirc&)'
/home/gadial/test/niklasso/tip/tip/Main.cc:159: undefined reference to `Tip::checkLivenessBiere(Tip::TipCirc&, int)'
/home/gadial/test/niklasso/tip/tip/Main.cc:157: undefined reference to`Tip::checkLiveness(Tip::TipCirc&, int)'
/home/gadial/test/niklasso/tip/tip/Main.cc:161: undefined reference to `Tip::bmcLivenessBiere(Tip::TipCirc&, int)'
collect2: error: ld returned 1 exit status
make: **\* [build/release/bin/tip] Error 1

**Comment by niklasso** [comment]
I can't tell what went wrong here. Can you show exactly what you did before this?

**Comment by gadial** [comment]
Here is the whole story (on a machine which already has minisat and mcl installed in the default directories):

gadial@ubuntu:~/Projects/test$ git clone https://github.com/niklasso/tip.git
Cloning into 'tip'...
remote: Counting objects: 1172, done.
remote: Compressing objects: 100% (316/316), done.
remote: Total 1172 (delta 865), reused 1163 (delta 856)
Receiving objects: 100% (1172/1172), 255.50 KiB | 115 KiB/s, done.
Resolving deltas: 100% (865/865), done.
gadial@ubuntu:~/Projects/test$ cd tip
gadial@ubuntu:~/Projects/test/tip$ make
Compiling: build/release/tip/Main.o
Compiling: build/release/tip/TipCirc.o
Linking Static Library: build/release/lib/libtip.a
Linking Binary: build/release/bin/tip
build/release/lib/libtip.a(TipCirc.o): In function `Tip::TipCirc::bmc(unsigned int, unsigned int, Tip::TipCirc::BmcVersion)':
/home/gadial/Projects/test/tip/tip/TipCirc.cc:101: undefined reference to`Tip::simpBmc2(Tip::TipCirc&, unsigned int, unsigned int)'
/home/gadial/Projects/test/tip/tip/TipCirc.cc:96: undefined reference to `Tip::basicBmc(Tip::TipCirc&, unsigned int, unsigned int, bool)'
/home/gadial/Projects/test/tip/tip/TipCirc.cc:98: undefined reference to`Tip::simpBmc(Tip::TipCirc&, unsigned int, unsigned int)'
build/release/lib/libtip.a(TipCirc.o): In function `Tip::TipCirc::sce(bool, bool)':
/home/gadial/Projects/test/tip/tip/TipCirc.cc:107: undefined reference to`Tip::semanticConstraintExtraction(Tip::TipCirc&, bool, bool)'
build/release/lib/libtip.a(TipCirc.o): In function `Tip::TipCirc::trip(Tip::RipBmcMode)':
/home/gadial/Projects/test/tip/tip/TipCirc.cc:111: undefined reference to`Tip::relativeInduction(Tip::TipCirc&, Tip::RipBmcMode)'
build/release/tip/Main.o: In function `main':
/home/gadial/Projects/test/tip/tip/Main.cc:123: undefined reference to`Tip::temporalDecompositionSmart(Tip::TipCirc&, unsigned int, unsigned int)'
/home/gadial/Projects/test/tip/tip/Main.cc:131: undefined reference to `Tip::substituteConstraints(Tip::TipCirc&)'
/home/gadial/Projects/test/tip/tip/Main.cc:133: undefined reference to`Tip::removeUnusedLogic(Tip::TipCirc&)'
/home/gadial/Projects/test/tip/tip/Main.cc:138: undefined reference to `Tip::embedConstraints(Tip::TipCirc&)'
/home/gadial/Projects/test/tip/tip/Main.cc:141: undefined reference to`Tip::embedFairness(Tip::TipCirc&)'
/home/gadial/Projects/test/tip/tip/Main.cc:147: undefined reference to `Tip::writeLivenessBiere(Tip::TipCirc&, int, char const*)'
/home/gadial/Projects/test/tip/tip/Main.cc:115: undefined reference to`Tip::removeUnusedLogic(Tip::TipCirc&)'
/home/gadial/Projects/test/tip/tip/Main.cc:126: undefined reference to `Tip::fairnessConstraintExtraction(Tip::TipCirc&, int, bool)'
/home/gadial/Projects/test/tip/tip/Main.cc:120: undefined reference to`Tip::extractSafety(Tip::TipCirc&)'
/home/gadial/Projects/test/tip/tip/Main.cc:159: undefined reference to `Tip::checkLivenessBiere(Tip::TipCirc&, int)'
/home/gadial/Projects/test/tip/tip/Main.cc:157: undefined reference to`Tip::checkLiveness(Tip::TipCirc&, int)'
/home/gadial/Projects/test/tip/tip/Main.cc:161: undefined reference to `Tip::bmcLivenessBiere(Tip::TipCirc&, int)'
collect2: error: ld returned 1 exit status
make: **\* [build/release/bin/tip] Error 1

**Comment by niklasso** [comment]
I see. When I was last working on tip I had switched to a CMake-based buildsystem and this GNU Make version has bitrotted a bit. I pushed an update. Can you check if it works?

You may also want to check out my "supermini" project that is just a container project that helps build some minisat-based software (tip included). If you're familiar with CMake it may help a bit. Otherwise, maybe not so much...

**Comment by gadial** [comment]
Seems to compile now. Thanks!

Gadi
